services:
  asterisk:
    image: andrius/asterisk:latest   # или mlan/asterisk
    container_name: asterisk
    network_mode: host               # важно для RTP!
    volumes:
      - ./config:/etc/asterisk
    restart: unless-stopped

  # Контейнер с rag-моделью НЕ ГОТОВ! УХОДИМ ОТ GROQ и вообще идем на локальный инференс
  ai_service:
    build: ./ai_service
    container_name: ai_service
    restart: unless-stopped
    volumes:
    # Путь к векторной базе данных, мы переместим папку из корня в папку приложения
      - ./ai_service/chroma_db:/app/services/embeddings_service/chroma_db
    # Путь к предварительно загруженым моделям, можно грузить в рантайме, но это длительная операция
      - ./ai_service/models:/app/services/embeddings_service/models
    env_file:
      - ./ai_service/.env
    networks:
      - internal
    ports:
      - "8005:8005"
    # mem_limit: 160m
    # cpus: "0.2"

  voice_service:
    build: ./voice_service
    container_name: voice_service
    restart: unless-stopped
    ports:
      - "8010:8010"
    volumes:
      - voice_torch_cache:/app/.torch_cache
    environment:
      - AI_SERVICE_URL=http://ai_service:8005
    networks:
      - internal
    depends_on:
      - ai_service

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  voice_torch_cache:

