[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_signaling_address=127.0.0.1
external_media_address=127.0.0.1

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_signaling_address=127.0.0.1
external_media_address=127.0.0.1

[1000]
type=endpoint
context=incoming
disallow=all
allow=ulaw
allow=alaw
auth=1000
aors=1000
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1000]
type=auth
auth_type=userpass
username=1000
password=secret1000

[1000]
type=aor
max_contacts=2
remove_existing=yes
